---
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Utiliza la base de datos de R llamada larynx, del paquete KMsurv, y realice lo siguiente:

Explique sus resultados.

#Análisis descriptivo

1.- Realice un análisis descriptivo sobre el tiempo de supervivencia de los sujetos, además de sus características generales y particulares.

#Kaplan-Meier

2.- Con el estimador de Kaplan-Meier para la función de supervivencia S(t), calcule y grafique:

## S(t) poblacional

## S(t) por estadio de la enfermedad

## S(t) por grupos de edad

Identifique las variables que afectan el tiempo de supervivencia. Incluya los intervalos del 95\% confianza.

# Pruebas Log-Rank con \alpha=0.05

## Por estadio

Compare las funciones de supervivencia por estadio, es decir, realice el contraste 
de hipótesis:

$$H_0: S_j(t)=S_k(t) \forall t >0, \forall j,k\textbf{.         vs        .} H_a: S_j(t) \not = S_k(t);\textbf{p.a }t>0, p.a j\not = k.$$

## Por grupo de edad

Compare las funciones de supervivencia por grupos de edad
